'use server'
// src/components/cases/caseActions.ts
// Server Actions for cases and case_material_usage.
//
// Key design points:
//   - case_code is auto-generated by the DB trigger fn_gen_case_number()
//     so we never pass it on insert — the DB sets it.
//   - material_cost on cases is auto-updated by fn_rollup_case_material_cost()
//     trigger when case_material_usage rows are inserted/deleted.
//   - When we insert a case_material_usage row, the DB trigger
//     fn_deduct_stock_on_case_usage() auto-inserts a stock_movements 'out' row.
//   - unit_cost_at_time is snapshotted from materials.cost_per_unit at insert time.

import { revalidatePath } from 'next/cache'
import { getServerSupabaseClient } from '@/lib/supabase/server'
import { caseSchema, addMaterialUsageSchema, type CaseFormValues, type AddMaterialUsageValues } from './caseSchema'

export type ActionResult =
  | { success: true; id?: string }
  | { success: false; error: string }

function dbErr(e: { code?: string; message: string }): ActionResult {
  if (e.code === '23505') return { success: false, error: 'A case with this code already exists.' }
  if (e.code === '23503') return { success: false, error: 'Referenced record no longer exists.' }
  if (e.code === 'P0004' || e.message?.includes('Insufficient stock')) {
    return { success: false, error: 'Insufficient stock for one or more materials.' }
  }
  return { success: false, error: e.message }
}

// ─── CREATE case ─────────────────────────────────────────────────────────────

export async function createCase(values: CaseFormValues): Promise<ActionResult> {
  const parsed = caseSchema.safeParse(values)
  if (!parsed.success) return { success: false, error: parsed.error.errors[0].message }

  const supabase = getServerSupabaseClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { success: false, error: 'Not authenticated' }

  // case_code is intentionally omitted — DB trigger generates it
  const { data, error } = await supabase
    .from('cases')
    .insert({ ...parsed.data })
    .select('id, case_code')
    .single()

  if (error) return dbErr(error)

  revalidatePath('/cases')
  revalidatePath('/dashboard')
  return { success: true, id: data.id }
}

// ─── UPDATE case ─────────────────────────────────────────────────────────────

export async function updateCase(id: string, values: CaseFormValues): Promise<ActionResult> {
  const parsed = caseSchema.safeParse(values)
  if (!parsed.success) return { success: false, error: parsed.error.errors[0].message }

  const supabase = getServerSupabaseClient()

  // Never update case_code or material_cost (both managed by DB)
  const { patient_name, clinic_name, doctor_name, work_type, status,
          tooth_numbers, shade, received_date, due_date, completed_date,
          labor_cost, machine_cost, final_price, notes } = parsed.data

  const { error } = await supabase
    .from('cases')
    .update({ patient_name, clinic_name, doctor_name, work_type, status,
              tooth_numbers, shade, received_date, due_date, completed_date,
              labor_cost, machine_cost, final_price, notes })
    .eq('id', id)

  if (error) return dbErr(error)

  revalidatePath('/cases')
  revalidatePath(`/cases/${id}`)
  revalidatePath('/dashboard')
  return { success: true }
}

// ─── DELETE case (soft — set status to cancelled) ────────────────────────────

export async function deleteCase(id: string): Promise<ActionResult> {
  const supabase = getServerSupabaseClient()
  const { error } = await supabase
    .from('cases')
    .update({ status: 'cancelled' })
    .eq('id', id)

  if (error) return dbErr(error)

  revalidatePath('/cases')
  revalidatePath('/dashboard')
  return { success: true }
}

// ─── ADD material to case ────────────────────────────────────────────────────
// Fetches the material's current cost_per_unit and snapshots it as unit_cost_at_time.
// The DB trigger then auto-deducts stock and rolls up material_cost on the case.

export async function addMaterialToCase(
  caseId: string,
  values: AddMaterialUsageValues
): Promise<ActionResult> {
  const parsed = addMaterialUsageSchema.safeParse(values)
  if (!parsed.success) return { success: false, error: parsed.error.errors[0].message }

  const supabase = getServerSupabaseClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { success: false, error: 'Not authenticated' }

  // 1. Snapshot the current cost_per_unit and check available quantity
  const { data: material, error: matErr } = await supabase
    .from('materials')
    .select('cost_per_unit, name, quantity')
    .eq('id', parsed.data.material_id)
    .single()

  if (matErr || !material) return { success: false, error: 'Material not found.' }

  // 2. App-level stock guard (DB trigger is the hard enforcement)
  const available = Number(material.quantity)
  const requested = parsed.data.quantity_used
  if (requested > available) {
    return {
      success: false,
      error: `Insufficient stock for "${material.name}". Available: ${available}, requested: ${requested}.`,
    }
  }

  // 3. Insert usage row — DB triggers auto-create stock movement and roll up material_cost
  const { error } = await supabase
    .from('case_material_usage')
    .insert({
      case_id:           caseId,
      material_id:       parsed.data.material_id,
      quantity_used:     parsed.data.quantity_used,
      unit_cost_at_time: Number(material.cost_per_unit),
      notes:             parsed.data.notes ?? null,
    })

  if (error) return dbErr(error)

  revalidatePath(`/cases/${caseId}`)
  revalidatePath('/stock')
  return { success: true }
}

// ─── REMOVE material from case ───────────────────────────────────────────────
// Note: the DB trigger that deducted stock on INSERT does NOT reverse on DELETE.
// Stock is NOT returned — this is intentional. If the material needs to go
// back into stock, the user should create a 'return' stock movement manually.

export async function removeMaterialFromCase(
  caseId: string,
  usageId: string
): Promise<ActionResult> {
  const supabase = getServerSupabaseClient()
  const { error } = await supabase
    .from('case_material_usage')
    .delete()
    .eq('id', usageId)
    .eq('case_id', caseId) // safety check

  if (error) return dbErr(error)

  revalidatePath(`/cases/${caseId}`)
  return { success: true }
}
